[package]
name = "atproto-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
tokio = { version = "1.43.0", features = ["rt", "macros", "time", "io-std"] }
tokio-tungstenite = { version = "0.26.1", features = ["native-tls"] }
